In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import logging

Generate some data:

In [3]:
from batchglm.api.models.nb_glm import Simulator

sim = Simulator(num_observations=2000, num_features=100)
sim.generate_sample_description(num_batches=0)
sim.generate()

# count data
X = sim.X
# sample description
sample_description = sim.sample_description

The sample description should be a pandas DataFrame with `num_observations` rows.
Each column should represent a property of the dataset.

The module `batchglm.api.data` contains some helper functions which can be useful to create this sample description:

- `sample_description_from_anndata()`
- `sample_description_from_xarray()`

In [4]:
sample_description

             condition
observations
0                    0
1                    1
2                    0
3                    1
4                    0
5                    1
6                    0
7                    1
8                    0
9                    1
10                   0
11                   1
12                   0
13                   1
14                   0
15                   1
16                   0
17                   1
18                   0
19                   1
20                   0
21                   1
22                   0
23                   1
24                   0
25                   1
26                   0
27                   1
28                   0
29                   1
...                ...
1970                 0
1971                 1
1972                 0
1973                 1
1974                 0
1975                 1
1976                 0
1977                 1
1978                 0
1979                 1
1980                 0
1981                 1
1982                 0
1983                 1
1984                 0
1985                 1
1986                 0
1987                 1
1988                 0
1989                 1
1990                 0
1991                 1
1992                 0
1993                 1
1994                 0
1995                 1
1996                 0
1997                 1
1998                 0
1999                 1

[2000 rows x 1 columns]

Run differential expression test:

In [5]:
logging.getLogger("tensorflow").setLevel(logging.WARNING)
logging.getLogger("batchglm").setLevel(logging.INFO)
logging.getLogger("diffxpy").setLevel(logging.INFO)

import diffxpy as de

test = de.test_lrt(
    data=sim.X,
    full_formula="~ 1 + condition",
    reduced_formula="~ 1",
    sample_description=sim.sample_description
)

Estimating model...
Using closed-form MLE initialization for mean
Using closed-form MME initialization for dispersion
Beginning with training sequence #1
Training sequence #1 complete
Estimation model ready
Estimating model...
Beginning with training sequence #1
Training sequence #1 complete
Beginning with training sequence #2
Training sequence #2 complete
Estimation model ready

The p-/q-values can be obtained by calling test.pval / test.qval:

In [4]:
test.qval

array([1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.33215661e-12,
       1.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.00000000e+00,
       0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 7.69690171e-06, 0.00000000e+00, 0.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       0.00000000e+00, 1.00000000e+00, 1.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 1.00000000e+00, 1.00000000e+00, 0.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 0.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 1.00000000e+00])

test.summary() returns a pandas DataFrame with a quick overview of the test results:

In [ ]:
test.summary()